package com.henry.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		arp.addMapping("category", "id", Category.class);
		arp.addMapping("loginlog", "id", Loginlog.class);
		arp.addMapping("nav", "id", Nav.class);
		arp.addMapping("news", "id", News.class);
		arp.addMapping("newslist", "id", Newslist.class);
		arp.addMapping("upload", "id", Upload.class);
	}
}

