package com.henry.common.model;

import com.henry.common.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {

    public Account removeSensitiveInfo() {
        remove("password", "salt");
        return this;
    }


	
}
