package com.henry.common.model;

import com.henry.common.model.base.BaseLoginlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Loginlog extends BaseLoginlog<Loginlog> {
	
}
