package com.henry.common.model;

import com.henry.common.model.base.BaseNav;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Nav extends BaseNav<Nav> {

    private List<Nav> children = new ArrayList<>(); //子导航栏

    public List<Nav> getChildren() {
        return children;
    }

    public void setChildren(List<Nav> children) {
        this.children = children;
    }

}
