package com.henry.common.model;

import com.henry.common.model.base.BaseNewslist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newslist extends BaseNewslist<Newslist> {
	
}
