package com.henry.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUpload<M extends BaseUpload<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setGroupId(java.lang.String groupId) {
		set("groupId", groupId);
	}
	
	public java.lang.String getGroupId() {
		return getStr("groupId");
	}

	public void setFileSize(java.lang.Double fileSize) {
		set("fileSize", fileSize);
	}
	
	public java.lang.Double getFileSize() {
		return getDouble("fileSize");
	}

	public void setFileName(java.lang.String fileName) {
		set("fileName", fileName);
	}
	
	public java.lang.String getFileName() {
		return getStr("fileName");
	}

}
