package com.henry.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setContent(byte[] content) {
		set("content", content);
	}
	
	public byte[] getContent() {
		return get("content");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setFileGroupId(java.lang.String fileGroupId) {
		set("fileGroupId", fileGroupId);
	}
	
	public java.lang.String getFileGroupId() {
		return getStr("fileGroupId");
	}

}
