package com.henry.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNav<M extends BaseNav<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setHref(java.lang.String href) {
		set("href", href);
	}
	
	public java.lang.String getHref() {
		return getStr("href");
	}

	public void setSpread(java.lang.String spread) {
		set("spread", spread);
	}
	
	public java.lang.String getSpread() {
		return getStr("spread");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public void setOrder(java.lang.Integer order) {
		set("order", order);
	}
	
	public java.lang.Integer getOrder() {
		return getInt("order");
	}

}
