package com.henry.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewslist<M extends BaseNewslist<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setNewsName(java.lang.String newsName) {
		set("newsName", newsName);
	}
	
	public java.lang.String getNewsName() {
		return getStr("newsName");
	}

	public void setNewsAuthor(java.lang.String newsAuthor) {
		set("newsAuthor", newsAuthor);
	}
	
	public java.lang.String getNewsAuthor() {
		return getStr("newsAuthor");
	}

	public void setNewsStatus(java.lang.String newsStatus) {
		set("newsStatus", newsStatus);
	}
	
	public java.lang.String getNewsStatus() {
		return getStr("newsStatus");
	}

	public void setNewsLook(java.lang.String newsLook) {
		set("newsLook", newsLook);
	}
	
	public java.lang.String getNewsLook() {
		return getStr("newsLook");
	}

	public void setIsShow(java.lang.String isShow) {
		set("isShow", isShow);
	}
	
	public java.lang.String getIsShow() {
		return getStr("isShow");
	}

	public void setNewsTime(java.util.Date newsTime) {
		set("newsTime", newsTime);
	}
	
	public java.util.Date getNewsTime() {
		return get("newsTime");
	}

	public void setAbstract(java.lang.String _abstract) {
		set("abstract", _abstract);
	}
	
	public java.lang.String getAbstract() {
		return getStr("abstract");
	}

	public void setCategoryId(java.lang.String categoryId) {
		set("categoryId", categoryId);
	}
	
	public java.lang.String getCategoryId() {
		return getStr("categoryId");
	}

}
