package com.henry.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategory<M extends BaseCategory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCategoryName(java.lang.String categoryName) {
		set("categoryName", categoryName);
	}
	
	public java.lang.String getCategoryName() {
		return getStr("categoryName");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}
	
	public java.lang.String getLevel() {
		return getStr("level");
	}

	public void setFatherId(java.lang.Integer fatherId) {
		set("fatherId", fatherId);
	}
	
	public java.lang.Integer getFatherId() {
		return getInt("fatherId");
	}

}
